# Generated by Django 2.1.5 on 2020-03-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='profile_pics'),
        ),
    ]
