# Generated by Django 2.1.5 on 2020-03-16 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icine', '0003_auto_20200316_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
