# Generated by Django 2.1.5 on 2020-03-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200313_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='motto',
            field=models.TextField(default='Movie lover', max_length=128),
        ),
    ]
